### ISSUE TITLE
Notification 英文被截断

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#298]
![image](https://user-images.githubusercontent.com/38368040/199688363-4963ce57-3a1b-467d-9eb9-8a3ccf246e85.png)

**Comment by LuckyFBB** [comment]
修改方式
```css
.ant-notification-notice-with-icon .ant-notification-notice-description{
    word-wrap: break-word;
}
```
